import type { TranscriptSegment as RealtimeTranscriptSegment } from "./realtime-transcription";

export interface Highlight {
  id: string;
  timestamp: number;
  label?: string;
  /** 周辺のテキスト文脈 */
  context?: string;
}

export interface TranscriptSegment {
  text: string;
  startTime: number;
  endTime: number;
  speaker?: string;
  /** 翻訳テキスト */
  translatedText?: string;
}

export interface Transcript {
  text: string;
  segments: TranscriptSegment[];
  language: string;
  processedAt: Date;
  /** 翻訳情報 */
  translation?: {
    targetLanguage: string;
    text: string;
  };
}

export interface Summary {
  overview: string;
  keyPoints: string[];
  actionItems: string[];
  processedAt: Date;
}

export type TemplateType = 'general' | 'meeting' | 'interview' | 'lecture' | 'custom';

export interface SummaryTemplate {
  id: string;
  name: string;
  type: TemplateType;
  prompt: string; // Custom prompt for LLM
  sections: {
    name: string;
    description: string;
    itemCount?: number; // For lists like bullet points
  }[];
  isDefault: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface QAReference {
  startTime: number;
  endTime: number;
  text: string;
}

export interface QAMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  references?: QAReference[];
}

export interface Tag {
  id: string;
  name: string;
  color?: string;
  isAutoGenerated: boolean;
  confidence?: number; // 0-1
}

export interface ActionItem {
  id: string;
  text: string;
  priority: 'high' | 'medium' | 'low';
  dueDate?: Date;
  completed: boolean;
  isAutoGenerated: boolean;
  confidence?: number; // 0-1
  associatedTimestamp?: number; // Timestamp in recording where this action was mentioned
}

export interface SentimentAnalysis {
  overallSentiment: 'positive' | 'neutral' | 'negative';
  score: number; // -1 to 1
  confidence: number; // 0-1
  emotions: {
    joy: number;
    sadness: number;
    anger: number;
    fear: number;
    surprise: number;
    disgust: number;
  };
  summary: string; // Brief summary of emotional tone
  processedAt: Date;
}

export interface Keyword {
  id: string;
  text: string;
  importance: 'high' | 'medium' | 'low';
  confidence: number; // 0-1
  frequency: number; // How many times mentioned
  startIndex: number; // First occurrence in text
}

export interface Analysis {
  overview: string;
  keyPoints: string[];
  tags: Tag[];
  actionItems: ActionItem[];
  keywords: Keyword[];
  sentiment: SentimentAnalysis;
  processedAt: Date;
}

export interface Recording {
  id: string;
  title: string;
  audioUri: string;
  duration: number;
  createdAt: Date;
  updatedAt: Date;
  highlights: Highlight[];
  notes: string;
  transcript?: Transcript;
  summary?: Summary;
  summaryTemplateType?: TemplateType;
  analysis?: Analysis;
  tags: Tag[];
  actionItems: ActionItem[];
  sentiment?: SentimentAnalysis;
  keywords: Keyword[];
  qaHistory: QAMessage[];
  status: 'recording' | 'saved' | 'transcribing' | 'transcribed' | 'analyzing' | 'analyzed';
  /** リアルタイム文字起こし（録音中の一時データ） */
  realtimeTranscript?: {
    segments: RealtimeTranscriptSegment[];
    lastUpdated: Date;
  };
  /** 正規化済み波形データ (0-1) */
  waveformData?: number[];
}

/**
 * 録音セッションのドラフト（自動保存用）
 * アプリがクラッシュした場合の復元に使用
 */
export interface RecordingDraft {
  id: string;
  startedAt: Date;
  lastSavedAt: Date;
  duration: number;
  highlights: Highlight[];
  realtimeEnabled: boolean;
  realtimeSegments?: RealtimeTranscriptSegment[];
  meteringHistory: number[];
}
