import type { Meta, StoryObj } from "@storybook/react";
import { ScrollView } from "react-native";
import { RecordingCard } from "@/packages/components/recording-card";
import type { Recording } from "@/packages/types/recording";

const meta: Meta<typeof RecordingCard> = {
  title: "Notes/RecordingCard",
  component: RecordingCard,
  decorators: [
    (Story) => (
      <ScrollView style={{ flex: 1, backgroundColor: "#f5f5f5", padding: 16 }}>
        <Story />
      </ScrollView>
    ),
  ],
  argTypes: {
    onPress: { action: "pressed" },
    onDelete: { action: "deleted" },
    onToggleSelection: { action: "toggled" },
  },
};

export default meta;

type Story = StoryObj<typeof RecordingCard>;

const baseRecording: Recording = {
  id: "1",
  title: "週次ミーティング",
  audioUri: "",
  duration: 1800,
  createdAt: new Date(),
  updatedAt: new Date(),
  status: "saved",
  highlights: [],
  notes: "",
  tags: [],
  actionItems: [],
  keywords: [],
  qaHistory: [],
};

export const BasicCard: Story = {
  args: {
    recording: baseRecording,
    columns: 1,
    isSelectMode: false,
    isSelected: false,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const Transcribed: Story = {
  args: {
    recording: {
      ...baseRecording,
      status: "transcribed",
      transcript: {
        text: "今日のミーティングでは、プロジェクトの進捗状況について話し合いました。主なトピックは、新機能の開発状況、バグ修正の優先順位、そして来週のリリーススケジュールについてです。",
        segments: [],
        language: "ja",
        processedAt: new Date(),
      },
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const Analyzed: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "プロジェクト計画会議",
      status: "analyzed",
      transcript: {
        text: "今日のミーティングでは...",
        segments: [],
        language: "ja",
        processedAt: new Date(),
      },
      analysis: {
        overview: "プロジェクトの進捗確認と今後の計画について議論",
        keyPoints: ["開発は予定通り進行中", "テストフェーズは来週開始"],
        tags: [{ id: "1", name: "プロジェクト", isAutoGenerated: true, confidence: 0.9 }],
        actionItems: [{ id: "1", text: "ドキュメントの更新", priority: "medium", completed: false, isAutoGenerated: true, confidence: 0.8 }],
        keywords: [{ id: "1", text: "進捗", importance: "high", confidence: 0.9, frequency: 3, startIndex: 0 }],
        sentiment: {
          overallSentiment: "positive",
          score: 0.5,
          confidence: 0.8,
          emotions: { joy: 0.3, sadness: 0.1, anger: 0.05, fear: 0.05, surprise: 0.1, disgust: 0.05 },
          summary: "前向きなトーン",
          processedAt: new Date(),
        },
        processedAt: new Date(),
      },
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const WithTags: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "アイデアブレスト",
      status: "transcribed",
      tags: [
        { id: "1", name: "アイデア", color: "#3B82F6", isAutoGenerated: true },
        { id: "2", name: "ブレスト", color: "#10B981", isAutoGenerated: true },
        { id: "3", name: "重要", color: "#EF4444", isAutoGenerated: false },
        { id: "4", name: "フォローアップ", isAutoGenerated: false },
      ],
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const WithMetadata: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "1on1ミーティング",
      status: "analyzed",
      highlights: [
        { id: "1", timestamp: 120 },
        { id: "2", timestamp: 350, label: "重要" },
      ],
      actionItems: [
        { id: "1", text: "レビューを完了する", priority: "high", completed: false, isAutoGenerated: true },
        { id: "2", text: "報告書を提出", priority: "medium", completed: true, isAutoGenerated: true },
        { id: "3", text: "チームに共有", priority: "low", completed: false, isAutoGenerated: false },
      ],
      keywords: [
        { id: "1", text: "プロジェクト", importance: "high", frequency: 5, confidence: 0.9, startIndex: 0 },
        { id: "2", text: "リリース", importance: "medium", frequency: 3, confidence: 0.8, startIndex: 50 },
      ],
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const Transcribing: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "処理中の録音",
      status: "transcribing",
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const SelectMode: Story = {
  args: {
    recording: baseRecording,
    columns: 1,
    isSelectMode: true,
    isSelected: false,
    onPress: () => {},
    onDelete: () => {},
    onToggleSelection: () => {},
  },
};

export const Selected: Story = {
  args: {
    recording: baseRecording,
    columns: 1,
    isSelectMode: true,
    isSelected: true,
    onPress: () => {},
    onDelete: () => {},
    onToggleSelection: () => {},
  },
};

export const LongTitle: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "これは非常に長いタイトルの録音で、モバイル画面では切り詰められる可能性があります",
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const ShortDuration: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "短いメモ",
      duration: 15,
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};

export const LongDuration: Story = {
  args: {
    recording: {
      ...baseRecording,
      title: "長時間録音",
      duration: 7200,
    },
    columns: 1,
    onPress: () => {},
    onDelete: () => {},
  },
};
